Plex-Inc/bricks

- .github/workflows/gh_pages_deploy.yml
> Create build storybook workflow

- .gitignore
> add storybook build statis to .gitignore

- .github/workflows/canary.yml
> add canary workflow

- .github/workflows/canary.yml
> Fix canary workflow

- .github/workflows/canary.yml
> ci(workflow): use pat token instead actions/create-github-app-token@v1

- src/components/Tab/Tab.module.css
- src/components/Tab/Tab.stories.tsx
- src/components/Tab/Tab.tsx
> Tab component

- src/components/RadioButton/RadioButton.module.css
- src/components/RadioButton/RadioButton.stories.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/index.ts
> RadioButton component

- src/components/Input/Input.module.css
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
> Input component

- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/Textarea.tsx
- src/components/index.ts
> Add export components

- vite.config.ts
> Remove *.stories.d.ts from build

- .github/workflows/release.yml
> Fix npm release workflow

- src/components/Button/Button.module.css
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
> edit component button

- src/components/Loader/Loader.module.css
- src/components/Loader/Loader.stories.tsx
- src/components/Loader/Loader.tsx
- src/components/index.ts
> Loader component

- src/components/Spinner/Spinner.module.css
- src/components/Spinner/Spinner.stories.tsx
- src/components/Spinner/Spinner.tsx
- src/components/index.ts
> Spinner component

- .storybook/index.css
- .storybook/preview.tsx
> Add theme to storybook

- .storybook/index.css
- src/components/Avatar/Avatar.module.css
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/Avatar.tsx
- src/components/Circle/Circle.module.css
- src/components/Circle/Circle.stories.tsx
- src/components/Circle/Circle.tsx
- src/components/index.ts
- src/utils/getInitials.ts
- src/utils/stringToColor.ts
> Avatar component

- .storybook/index.css
- src/components/Switch/Switch.module.css
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/index.ts
> Switch component

- src/components/Text/Text.tsx
> FIX: Text component

- src/components/Loader/Loader.module.css
- src/components/Loader/Loader.tsx
> Fix loader component

- src/components/Modal/Modal.module.css
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/components/index.ts
> Refactor Modal component

- src/components/FormControl/FormControl.stories.tsx
- src/components/FormControl/FormControl.tsx
- src/components/index.ts
- src/utils/index.ts
- src/utils/setRefs.ts
> FormControl

- src/components/Button/Button.module.css
- src/components/Checkbox/Checkbox.module.css
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Input/Input.module.css
- src/components/Input/Input.tsx
- src/components/Loader/Loader.tsx
- src/components/MenuItem/MenuItem.stories.tsx
- src/components/Modal/Modal.tsx
- src/components/Popup/Popup.stories.tsx
- src/components/RadioButton/RadioButton.module.css
- src/components/RadioButton/RadioButton.stories.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/Tab/Tab.module.css
- src/components/Text/Text.module.css
- src/components/Text/Text.stories.tsx
- src/components/Text/Text.tsx
- src/components/Textarea/Textarea.module.css
> make edits from the designer

- src/components/Divider/Divider.module.css
- src/components/Divider/Divider.stories.tsx
- src/components/Divider/Divider.tsx
- src/components/index.ts
> Divider component

- src/components/VerificationInput/VerificationInput.module.css
- src/components/VerificationInput/VerificationInput.stories.tsx
- src/components/VerificationInput/VerificationInput.tsx
- src/components/index.ts
Resolve #66 
Related issues #<issue>, #<issue>
> Totp component

- src/components/index.ts
> FIX: export tabs component

- src/components/Pagination/Pagination.module.css
- src/components/Pagination/Pagination.stories.tsx
- src/components/Pagination/Pagination.tsx
- src/components/index.ts
- src/hooks/usePagination.ts
> Pagination component

- src/components/SwitchTheme/SwitchTheme.module.css
> fix: css variable

- src/components/VerificationInput/VerificationInput.stories.tsx
- src/components/VerificationInput/VerificationInput.tsx
> FIX: varification input should work on ctrl+v

- src/components/Button/Button.module.css
- src/components/Button/Button.tsx
> add disabled in button

- src/components/StatusBadge/StatusBadge.module.css
- src/components/StatusBadge/StatusBadge.stories.tsx
- src/components/StatusBadge/StatusBadge.tsx
- src/components/index.ts
> StatusBadge component

- src/components/Tab/Tab.tsx
> fix: tab component

- src/components/Badge/Badge.module.css
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
- src/components/index.ts
> Badge component

- src/components/Modal/Modal.module.css
- src/components/Modal/Modal.tsx
> FIX: Modal component

- src/components/Input/Input.module.css
> FIX: input component

- src/components/Badge/Badge.module.css
- src/components/Button/Button.module.css
- src/components/Checkbox/Checkbox.module.css
- src/components/MenuItem/MenuItem.module.css
- src/components/RadioButton/RadioButton.module.css
- src/components/Tab/Tab.module.css
> FIX: delete transition all on lib components

- src/components/Accordion/Accordion.module.css
- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
- src/components/index.ts
> Accordion component

- src/components/MenuItem/MenuItem.module.css
- src/components/MenuItem/MenuItem.stories.tsx
- src/components/MenuItem/MenuItem.tsx
> update menuItem component

- src/components/Skeleton/Skeleton.module.css
- src/components/Skeleton/Skeleton.stories.tsx
- src/components/Skeleton/Skeleton.tsx
- src/components/Table/Table.module.css
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/index.ts
> Table component

- src/components/Avatar/Avatar.module.css
- src/components/User/User.module.css
- src/components/User/User.stories.tsx
- src/components/User/User.tsx
- src/components/index.ts
> User component

- src/hooks/index.ts
- src/hooks/useIsMobile.ts
- src/utils/debounce.ts
> useIsMobile hook

- src/components/Dropdown/Dropdown.module.css
- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/index.ts
- src/hooks/useKeyboard.ts
Resolve #188 
https://github.com/user-attachments/assets/c942d82e-8847-4c72-96cd-46a5caef1725
> Dropdown component

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/hooks/index.ts
- src/hooks/useOnClickOutside.ts
> FIX: modal should close on esc and overlay click

- src/components/Textarea/Textarea.tsx
> Fix textarea

- package-lock.json
- package.json
> install @plex-inc/icons in component library

- .storybook/index.css
- src/components/Pagination/Pagination.module.css
- src/components/Pagination/Pagination.tsx
> FIX: pagination component

- src/components/FormControl/FormControl.stories.tsx
- src/components/FormControl/FormControl.tsx
> Add formControlTextError component
